"""add document deletion, findings, and hold document_id

Revision ID: 31eb53d6299b
Revises: baebeaf3f4be
Create Date: 2026-09-28 23:17:44.306970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31eb53d6299b'
down_revision: Union[str, None] = 'baebeaf3f4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('documents', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('deletion_reason', sa.Text(), nullable=True))
    op.add_column('preservation_holds', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'preservation_holds', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'preservation_holds', type_='foreignkey')
    op.drop_column('preservation_holds', 'document_id')
    op.drop_column('documents', 'deletion_reason')
    op.drop_column('documents', 'deleted_by')
    op.drop_column('documents', 'deleted_at')
    op.drop_column('documents', 'findings')
    # ### end Alembic commands ###
