"""add file metadata to documents, make text nullable

Revision ID: 38755030c7dc
Revises: 98b18e886683
Create Date: 2026-09-27 21:59:42.842370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38755030c7dc'
down_revision: Union[str, None] = '98b18e886683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('mime_type', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('file_hash', sa.String(), nullable=True))
    op.alter_column('documents', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('documents', 'file_hash')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'mime_type')
    # ### end Alembic commands ###
