"""initial schema

Revision ID: 98b18e886683
Revises: 
Create Date: 2026-09-27 11:47:59.267010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98b18e886683'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('claim_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('loss_date', sa.Date(), nullable=False),
    sa.Column('repair_status', sa.String(), nullable=False),
    sa.Column('upcoming_business_event', sa.Enum('REPAIR_AUTHORIZATION', 'CLAIM_CLOSURE', name='expirytrigger', native_enum=False), nullable=True),
    sa.Column('claimant', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('classification', sa.Enum('VEHICLE_PHOTOGRAPHS', 'POLICE_REPORT', 'REPAIR_APPRAISAL', 'VEHICLE_INSPECTION', 'RECORDED_STATEMENT', 'REPAIR_ESTIMATE', 'OTHER', name='documentclass', native_enum=False), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('litigation_signal', sa.Enum('ATTORNEY_REPRESENTATION', 'DEMAND_LETTER', 'RECORDS_REQUEST', 'NONE', name='litigationsignal', native_enum=False), nullable=True),
    sa.Column('litigation_confidence', sa.Float(), nullable=True),
    sa.Column('classification_status', sa.Enum('PENDING', 'CLASSIFIED', 'MANUAL_REVIEW', name='classificationstatus', native_enum=False), nullable=False),
    sa.Column('ai_provider', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preservation_holds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'ACTIVE', 'RELEASED', name='holdstatus', native_enum=False), nullable=False),
    sa.Column('trigger_reason', sa.Text(), nullable=False),
    sa.Column('trigger_source', sa.String(), nullable=False),
    sa.Column('trigger_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('released_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by', sa.String(), nullable=True),
    sa.Column('release_justification', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preservation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.Enum('CLAIM_CREATED', 'ANALYSIS_RUN', 'DOCUMENT_UPLOADED', 'DOCUMENT_CLASSIFIED', 'EVIDENCE_SATISFIED', 'LITIGATION_SIGNAL_DETECTED', 'HOLD_PROPOSED', 'HOLD_CONFIRMED', 'HOLD_RELEASED', 'OVERRIDE_APPLIED', name='preservationeventtype', native_enum=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('evidence_type', sa.Enum('VEHICLE_PHOTOGRAPHS', 'POLICE_REPORT', 'REPAIR_APPRAISAL', 'VEHICLE_INSPECTION', 'RECORDED_STATEMENT', 'REPAIR_ESTIMATE', name='evidencetype', native_enum=False), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('satisfied', sa.Boolean(), nullable=False),
    sa.Column('satisfied_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('satisfying_document_id', sa.Integer(), nullable=True),
    sa.Column('expiry_trigger', sa.Enum('REPAIR_AUTHORIZATION', 'CLAIM_CLOSURE', name='expirytrigger', native_enum=False), nullable=False),
    sa.Column('expired', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel', native_enum=False), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.ForeignKeyConstraint(['satisfying_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_items')
    op.drop_table('preservation_logs')
    op.drop_table('preservation_holds')
    op.drop_table('documents')
    op.drop_table('claims')
    # ### end Alembic commands ###
