"""add image analysis table and document image_analysis_status

Revision ID: baebeaf3f4be
Revises: 38755030c7dc
Create Date: 2026-09-28 19:14:33.466208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baebeaf3f4be'
down_revision: Union[str, None] = '38755030c7dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('evidence_type', sa.Enum('VEHICLE_PHOTOGRAPHS', 'POLICE_REPORT', 'REPAIR_APPRAISAL', 'VEHICLE_INSPECTION', 'RECORDED_STATEMENT', 'REPAIR_ESTIMATE', name='evidencetype', native_enum=False), nullable=False),
    sa.Column('vehicle_present', sa.Boolean(), nullable=False),
    sa.Column('damage_observed', sa.Boolean(), nullable=False),
    sa.Column('damage_regions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('image_quality', sa.Enum('CLEAR', 'BLURRY', 'OBSTRUCTED', 'TOO_DARK', name='imagequality', native_enum=False), nullable=False),
    sa.Column('relevance', sa.Enum('RELEVANT', 'NOT_RELEVANT', 'UNCERTAIN', name='imagerelevance', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    # server_default backfills existing rows (documents predating this
    # migration are never images) — dropped right after so the Python-side
    # default is the only one going forward, matching every other enum
    # column in this schema.
    op.add_column(
        'documents',
        sa.Column(
            'image_analysis_status',
            sa.Enum('NOT_APPLICABLE', 'PENDING', 'ANALYZED', 'MANUAL_REVIEW', name='imageanalysisstatus', native_enum=False),
            nullable=False,
            server_default='NOT_APPLICABLE',
        ),
    )
    op.alter_column('documents', 'image_analysis_status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'image_analysis_status')
    op.drop_table('image_analyses')
    # ### end Alembic commands ###
